[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npx vite"
  targetPort = 5173
  publish = "public"
  functions = "netlify/functions"
  autoLaunch = false

[[redirects]]
  from = "/fiches-reflexives"
  to = "/.netlify/functions/fiche-list"
  status = 200

[[redirects]]
  from = "/fiches-reflexives/:id"
  to = "/.netlify/functions/fiche-detail?id=:id"
  status = 200

[[redirects]]
  from = "/api/pdf/:id"
  to = "/.netlify/functions/pdf?id=:id"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/logout"
  status = 200
